[package]
name = "bloomfilter"
version = "0.1.0"
authors = ["wellls <wellschuan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1.0.3"
